# Generated by Django 6.0.2 on 2026-03-02 09:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom officiel de l'entreprise", max_length=255, unique=True)),
                ('siret', models.CharField(help_text='Numéro SIRET (14 chiffres)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'SIRET doit contenir 14 chiffres')])),
                ('contact_email', models.EmailField(help_text='Email de contact principal', max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\s\\+\\-\\(\\)]+$', 'Format de téléphone invalide')])),
                ('sector', models.CharField(choices=[('it', 'IT/Informatique'), ('secretariat', 'Secrétariat/Assistanat'), ('photographie ', 'Photographie/Vidéo'), ('jardinage', 'Jardinage'), ('manutention', 'Manutention/Déménagement'), ('securite', 'Sécurité/Gardiennage'), ('restauration', 'Restauration'), ('nettoyage', 'Nettoyage/Ménage'), ('autre', 'Autre')], help_text="Secteur d'activité principal", max_length=50)),
                ('address', models.CharField(help_text='Adresse complète', max_length=255)),
                ('city', models.CharField(help_text='Ville', max_length=100)),
                ('postal_code', models.CharField(help_text='Code postal', max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Code postal invalide (5 chiffres)')])),
                ('country', models.CharField(default='France', help_text='Pays', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description courte de l'entreprise", null=True)),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='company_logos/%Y/%m/%d/')),
                ('banner', models.ImageField(blank=True, help_text='Image de bannière', null=True, upload_to='company_banners/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('pending', 'En attente de vérification')], default='pending', help_text="Statut de l'entreprise", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="L'entreprise peut accéder à la plateforme")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['siret'], name='User_compan_siret_c8a06b_idx'), models.Index(fields=['contact_email'], name='User_compan_contact_246eba_idx'), models.Index(fields=['sector'], name='User_compan_sector_124a59_idx'), models.Index(fields=['is_active'], name='User_compan_is_acti_1c0d2b_idx'), models.Index(fields=['status'], name='User_compan_status_21c258_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('employee', 'Employé')], default='employee', help_text="Le rôle de l'utilisateur dans l'entreprise", max_length=20)),
                ('tel', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\s\\+\\-\\(\\)]+$', 'Format de téléphone invalide')])),
                ('avatar', models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='avatars/')),
                ('job_title', models.CharField(blank=True, help_text="Le poste ou titre de l'utilisateur dans l'entreprise", max_length=100, null=True)),
                ('bio', models.TextField(blank=True, help_text='Une courte biographie', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Email vérifié')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text="L'entreprise à laquelle l'utilisateur appartient", on_delete=django.db.models.deletion.CASCADE, related_name='users', to='User.company')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at', 'company', 'role', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='MgNJqYrnSuoJqJcciGW1S5RdUiFGSe9goeWntBvqVmM', help_text='Token unique de vérification', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration du token")),
                ('is_used', models.BooleanField(default=False, help_text='Token déjà utilisé')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text="L'utilisateur à vérifier", on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company', 'role'], name='User_user_company_3194ad_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='User_user_email_fb17fc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='User_user_is_veri_fafaeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['token'], name='User_emailv_token_64343f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user'], name='User_emailv_user_id_415b41_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['expires_at'], name='User_emailv_expires_a08e86_idx'),
        ),
    ]
