# Generated by Django 6.0.2 on 2026-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default='WMpSDB6ExGrQAaO143HiKm4cl_FFXOrqwDIwHKrkcq8', help_text='Token unique de vérification', max_length=255, unique=True),
        ),
    ]
