# Generated by Django 6.0.2 on 2026-03-06 14:09

import django.core.validators
import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_emailverificationtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, help_text='Token unique de vérification', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('it', 'IT/Informatique'), ('secretariat', 'Secrétariat/Assistanat'), ('photographie ', 'Photographie/Vidéo'), ('jardinage', 'Jardinage'), ('manutention', 'Manutention/Déménagement'), ('securite', 'Sécurité/Gardiennage'), ('restauration', 'Restauration'), ('nettoyage', 'Nettoyage/Ménage'), ('autre', 'Autre')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_posted', to='User.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text='Message de candidature')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_days', models.PositiveIntegerField(help_text='Délai estimé en jours')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('withdrawn', 'Retirée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_sent', to='User.company')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='User.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['sector'], name='User_missio_sector_55dd13_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['status'], name='User_missio_status_1a14d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['company'], name='User_missio_company_bfb5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['mission'], name='User_applic_mission_43e042_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['company'], name='User_applic_company_d729f9_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='User_applic_status_a40f6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('mission', 'company')},
        ),
    ]
