# Generated by Django 6.0.2 on 2026-03-09 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_supportadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_mission', 'Nouvelle mission disponible'), ('new_application', 'Nouvelle candidature reçue'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('review_received', 'Avis reçu')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='User.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='User_notifi_company_0e8520_idx'), models.Index(fields=['is_read'], name='User_notifi_is_read_7c0258_idx'), models.Index(fields=['-created_at'], name='User_notifi_created_ad5ae3_idx')],
            },
        ),
    ]
