# Generated by Django 6.0.2 on 2026-03-26 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Code postal du lieu de la mission', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Code postal invalide (5 chiffres)')]),
        ),
    ]
