# Generated by Django 6.0.2 on 2026-03-31 03:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_mission_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_tva',
            field=models.BooleanField(default=False, help_text='Le prestataire applique-t-il la TVA ?'),
        ),
        migrations.AddField(
            model_name='application',
            name='tva_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux de TVA en % (ex: 20.00 pour 20%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestataire_receives', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_client_pays', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payé'), ('released', 'Fonds versés au prestataire'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='User.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
