# Generated by Django 6.0.2 on 2026-04-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_application_apply_tva_application_tva_rate_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID client Stripe (cus_xxx) — créé au premier paiement', max_length=255, null=True)),
                ('stripe_account_id', models.CharField(blank=True, help_text="ID compte Connect Express (acct_xxx) — créé à l'onboarding", max_length=255, null=True)),
                ('stripe_onboarded', models.BooleanField(default=False, help_text='True quand le prestataire a terminé son onboarding Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe', to='User.company')),
            ],
            options={
                'verbose_name': 'Stripe Account',
            },
        ),
    ]
