# Generated by Django 6.0.2 on 2026-04-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_payment_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('pending_confirmation', 'En attente de confirmation'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='open', max_length=20),
        ),
    ]
