# Generated by Django 6.0.2 on 2026-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_mission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('pending_payment', 'En attente de paiement'), ('in_progress', 'En cours'), ('pending_confirmation', 'En attente de confirmation'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='open', max_length=20),
        ),
    ]
